import * as express from "express";
import * as userController from "./app/framework/controllers/user.controller";
import * as roleController from "./app/framework/controllers/role.controller";
import * as candidateController from "./app/framework/controllers/candidate.controller";
import * as capabilityController from "./app/framework/controllers/capability.controller";
import * as complexityController from "./app/framework/controllers/complexity.controller";
import * as proficienciesController from "./app/framework/controllers/proficiency.controller";
import * as industryController from "./app/framework/controllers/industry.controller";
import * as recruiterController from "./app/framework/controllers/recruiter.controller";
import * as jobProfileController from "./app/framework/controllers/job-profile.controller";
import * as userInterceptor from "./app/framework/interceptor/user.interceptor";
import {SearchController} from "./app/framework/search/controller/search.controller";
let AuthInterceptor = require('./app/framework/interceptor/auth.interceptor');
this.authInterceptor = new AuthInterceptor();


export function cnextInit(app: express.Application) { //todo add interceptor to authenticate
  let searchController = new SearchController();
  app.get('/api/industry',this.authInterceptor.requiresAuth, industryController.retrieve);
  app.post('/api/proficiency',this.authInterceptor.requiresAuth, proficienciesController.create);
  app.get('/api/proficiency', this.authInterceptor.requiresAuth,proficienciesController.retrieve);
  app.put('/api/proficiency',this.authInterceptor.requiresAuth, proficienciesController.update);
  app.post('/api/industry',this.authInterceptor.requiresAuth, industryController.create);
  app.put('/api/recruiter/:id/job', this.authInterceptor.requiresAuth,recruiterController.postJob);
  app.get('/api/industry/:id/role',this.authInterceptor.requiresAuth, roleController.retrieve);
  app.post('/api/candidate',this.authInterceptor.requiresAuth, userInterceptor.create, candidateController.create);
  app.put('/api/candidate/:id',this.authInterceptor.requiresAuth, candidateController.updateDetails);
  app.get('/api/candidate/:id',this.authInterceptor.requiresAuth, candidateController.retrieve);
  app.get('/api/industry/:id/roles/capability',this.authInterceptor.requiresAuth, capabilityController.retrieve);
  app.get('/api/industry/:id/roles/capability/complexity',this.authInterceptor.requiresAuth, complexityController.retrieve);
  app.get('/api/companysize', userController.getCompanySize);
  app.get('/api/function', this.authInterceptor.requiresAuth,userController.getFunction);
  app.put('/api/recruiter/:id',this.authInterceptor.requiresAuth, recruiterController.updateDetails);
  app.get('/api/recruiter/:id',this.authInterceptor.requiresAuth, recruiterController.retrieve);
  app.get('/api/capabilitymatrix/candidate/:id',this.authInterceptor.requiresAuth, candidateController.getCapabilityMatrix);
  app.get('/api/capabilitymatrix/recruiter/jobProfile/:id/',this.authInterceptor.requiresAuth, jobProfileController.getCapabilityMatrix);
  app.get('/api/recruiter/jobProfile/:id/candidates',this.authInterceptor.requiresAuth, searchController.getMatchingCandidates);
  app.get('/api/recruiter/jobProfile/:id',this.authInterceptor.requiresAuth, jobProfileController.retrieve);
  app.get('/api/candidate/:id/jobProfile',this.authInterceptor.requiresAuth, searchController.getMatchingJobProfiles);
  app.get('/api/candidate/:id/:candidateId',this.authInterceptor.requiresAuth, candidateController.retrieve);
  app.get('/api/candidateDetails/:id',this.authInterceptor.requiresAuth, candidateController.get);
  app.get('/api/candidate/:candidateId/matchresult/:jobId',this.authInterceptor.requiresAuth, candidateController.metchResult);
  app.get('/api/recruiter/jobProfile/:jobId/matchresult/:candidateId',this.authInterceptor.requiresAuth, jobProfileController.metchResultForJob);
  app.get('/api/candidate/:id/list/:listName',this.authInterceptor.requiresAuth, candidateController.getList);
  app.get('/api/recruiter/jobProfile/:id/list/:listName',this.authInterceptor.requiresAuth, recruiterController.getList);
  app.put('/api/candidate/:id/jobProfile/:profileId/:listName/:action',this.authInterceptor.requiresAuth, jobProfileController.apply);
  app.post('/api/recruiter/jobProfile/:id/candidates',this.authInterceptor.requiresAuth, jobProfileController.getQCardDetails);
  app.put('/api/recruiter/:recruiterId/jobProfile/:profileId/:listName/:candidateId/:action',this.authInterceptor.requiresAuth, jobProfileController.update);
  app.get('/api/filterlist',this.authInterceptor.requiresAuth, recruiterController.getFilterList);
  app.get('/api/releventindustries',this.authInterceptor.requiresAuth, industryController.getReleventIndustryList);
  app.get('/api/recruiter/:id/jobprofile/:jobId',this.authInterceptor.requiresAuth, recruiterController.getCompareDetailsOfCandidate);
}
