export class ConstVariables {
  public static LOWER_LIMIT_FOR_SEARCH_RESULT = 10;
  public static MAXIMUM_QCARD_FOR_SEARCH_RESULT_RESPONSE = 10;
  public static DIFFERENCE_IN_COMPLEXITY_SCENARIO = 10;
  public static JOB__EXPIRIY_PERIOD= 2592000000;
  public static SHORT_LISTED_CANDIDATE: string = 'shortListed';
  public static CART_LISTED_CANDIDATE: string = 'cartListed';
  public static REJECTED_LISTED_CANDIDATE: string = 'rejectedList';
  public static APPLIED_CANDIDATE: string = 'applied';
  public static BLOCKED_CANDIDATE: string = 'blocked';
  public static AUTHENTICATION_JWT_KEY: string = 'thisisjwtsecret#@$#&(*0)%';
  public static AUTHENTICATION_ENCODED_SHARE_KEY:string = '$$$socialShare@$#*';
  public static BEST_MATCH_SORT='Best match';

  public static ActionsArray: Array<string> = [
    'ADDED_IN_TO_CART_BY_RECRUITER',
    'ADDED_IN_TO_REJECT_BY_RECRUITER',
    'ADDED_IN_TO_COMPARE_VIEW_BY_RECRUITER',
    'VIEWED_HALF_PROFILE_BY_RECRUITER',
    'VIEWED_FULL_PROFILE_BY_RECRUITER',
    'VIEWED_VALUE_PORTRAIT_BY_RECRUITER',
    'VIEWED_JOB_PROFILE_BY_CANDIDATE',
    'APPLIED_FOR_JOB_PROFILE_BY_CANDIDATE',
    'ADDED_INTO_NOT_INTERESTED',
    'REMOVED_FROM_CART_BY_RECRUITER',
    'REMOVED_FROM_REJECT_BY_RECRUITER',
    'REMOVED_FROM_COMPARE_VIEW_BY_RECRUITER',
    'REMOVED_FROM_NOT_INTERESTED',
  ];

}
export enum Actions  {
  ADDED_IN_TO_CART_BY_RECRUITER,
  ADDED_IN_TO_REJECT_BY_RECRUITER,
  ADDED_IN_TO_COMPARE_VIEW_BY_RECRUITER,
  VIEWED_HALF_PROFILE_BY_RECRUITER,
  VIEWED_FULL_PROFILE_BY_RECRUITER,
  VIEWED_VALUE_PORTRAIT_BY_RECRUITER,
  VIEWED_JOB_PROFILE_BY_CANDIDATE,
  APPLIED_FOR_JOB_PROFILE_BY_CANDIDATE,
  ADDED_INTO_NOT_INTERESTED,
  REMOVED_FROM_CART_BY_RECRUITER,
  REMOVED_FROM_REJECT_BY_RECRUITER,
  REMOVED_FROM_COMPARE_VIEW_BY_RECRUITER,
  REMOVED_FROM_NOT_INTERESTED,
  DEFAULT_VALUE = 999
  //append your new enum value at the end of the list DON'T MODIFY THE LIST
}
export enum CandidateProfileUpdateTrackServerSide {
  STEP_IS_ENTER_PROFILE_DETAILS,
  STEP_IS_COMPLETED_INDUSTRY_DETAILS,
  STEP_IS_COMPLETED_AREA_OF_WORK,
  STEP_IS_COMPLETED_CAPABILITIES,
  STEP_IS_COMPLETED_COMPLEXITIES,
  STEP_IS_ENTER_KEY_SKILLS,
  STEP_IS_COMPLETED_ADDITIONAL_DOMAIN_EXPOSURE,
  STEP_IS_ENTER_PROFESSIONAL_PREFERENCES,
  STEP_IS_ENTER_ABOUT_MYSELF,
  STEP_IS_ENTER_EMPLOYMENT_HISTORY,
  STEP_IS_ENTER_ACADEMIC_DETAILS,
  STEP_IS_ENTER_CERTIFICATION_DETAILS,
  STEP_IS_ENTER_AWARDS_DETAILS,
  STEP_IS_SUBMIT_DETAILS
}
