export class ConstVariables {
  public static LOWER_LIMIT_FOR_SEARCH_RESULT = 40;
  public static DIFFERENCE_IN_COMPLEXITY_SCENARIO = 10;
  public static SHORT_LISTED_CANDIDATE: string = 'shortListed';
  public static CART_LISTED_CANDIDATE: string = 'cartListed';
  public static REJECTED_LISTED_CANDIDATE: string = 'rejectedList';
  public static APPLIED_CANDIDATE: string = 'applied';
  public static BLOCKED_CANDIDATE: string = 'blocked';
  public static AUTHENTICATION_JWT_KEY: string = 'thisisjwtsecret#@$#&(*0)%';

}
export enum Actions  {
  ADDED_IN_TO_CART_BY_RECRUITER,
  ADDED_IN_TO_REJECT_BY_RECRUITER,
  ADDED_IN_TO_COMPARE_VIEW_BY_RECRUITER,
  VIEWED_HALF_PROFILE_BY_RECRUITER,
  VIEWED_FULL_PROFILE_BY_RECRUITER,
  VIEWED_VALUE_PORTRAIT_BY_RECRUITER,
  VIEWED_JOB_PROFILE_BY_CANDIDATE,
  APPLIED_FOR_JOB_PROFILE_BY_CANDIDATE,
  ADDED_INTO_NOT_INTERESTED,
  REMOVED_FROM_CART_BY_RECRUITER,
  REMOVED_FROM_REJECT_BY_RECRUITER,
  REMOVED_FROM_COMPARE_VIEW_BY_RECRUITER,
  REMOVED_FROM_NOT_INTERESTED,
  DEFAULT_VALUE = 999
}
;
